// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: machinetalk/protobuf/log.proto

package machinetalk_protobuf_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin *MsgOrigin `protobuf:"varint,10,req,name=origin,enum=machinetalk.MsgOrigin" json:"origin,omitempty"`
	Pid    *int32     `protobuf:"varint,20,req,name=pid" json:"pid,omitempty"`
	Level  *MsgLevel  `protobuf:"varint,30,req,name=level,enum=machinetalk.MsgLevel" json:"level,omitempty"`
	Tag    *string    `protobuf:"bytes,40,req,name=tag" json:"tag,omitempty"`   //  [(nanopb).max_size = 20];
	Text   *string    `protobuf:"bytes,50,req,name=text" json:"text,omitempty"` //  [(nanopb).max_size = 100];
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machinetalk_protobuf_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_machinetalk_protobuf_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_machinetalk_protobuf_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogMessage) GetOrigin() MsgOrigin {
	if x != nil && x.Origin != nil {
		return *x.Origin
	}
	return MsgOrigin_MSG_KERNEL
}

func (x *LogMessage) GetPid() int32 {
	if x != nil && x.Pid != nil {
		return *x.Pid
	}
	return 0
}

func (x *LogMessage) GetLevel() MsgLevel {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return MsgLevel_RTAPI_MSG_NONE
}

func (x *LogMessage) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

func (x *LogMessage) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

var File_machinetalk_protobuf_log_proto protoreflect.FileDescriptor

var file_machinetalk_protobuf_log_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x6b, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x6b, 0x1a, 0x21, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x20, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x6b, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xa9, 0x01, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x2e, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x0a, 0x20, 0x02, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x6b, 0x2e,
	0x4d, 0x73, 0x67, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x14, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03,
	0x70, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x1e, 0x20, 0x02,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x6b,
	0x2e, 0x4d, 0x73, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x28, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x74,
	0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x32, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x3a, 0x06, 0x92, 0x3f, 0x03, 0x48, 0x90, 0x03, 0x42, 0x2f,
	0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x6b, 0x69, 0x74, 0x2f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x74,
	0x61, 0x6c, 0x6b, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x67, 0x6f,
}

var (
	file_machinetalk_protobuf_log_proto_rawDescOnce sync.Once
	file_machinetalk_protobuf_log_proto_rawDescData = file_machinetalk_protobuf_log_proto_rawDesc
)

func file_machinetalk_protobuf_log_proto_rawDescGZIP() []byte {
	file_machinetalk_protobuf_log_proto_rawDescOnce.Do(func() {
		file_machinetalk_protobuf_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_machinetalk_protobuf_log_proto_rawDescData)
	})
	return file_machinetalk_protobuf_log_proto_rawDescData
}

var file_machinetalk_protobuf_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_machinetalk_protobuf_log_proto_goTypes = []interface{}{
	(*LogMessage)(nil), // 0: machinetalk.LogMessage
	(MsgOrigin)(0),     // 1: machinetalk.MsgOrigin
	(MsgLevel)(0),      // 2: machinetalk.MsgLevel
}
var file_machinetalk_protobuf_log_proto_depIdxs = []int32{
	1, // 0: machinetalk.LogMessage.origin:type_name -> machinetalk.MsgOrigin
	2, // 1: machinetalk.LogMessage.level:type_name -> machinetalk.MsgLevel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_machinetalk_protobuf_log_proto_init() }
func file_machinetalk_protobuf_log_proto_init() {
	if File_machinetalk_protobuf_log_proto != nil {
		return
	}
	file_machinetalk_protobuf_nanopb_proto_init()
	file_machinetalk_protobuf_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_machinetalk_protobuf_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_machinetalk_protobuf_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_machinetalk_protobuf_log_proto_goTypes,
		DependencyIndexes: file_machinetalk_protobuf_log_proto_depIdxs,
		MessageInfos:      file_machinetalk_protobuf_log_proto_msgTypes,
	}.Build()
	File_machinetalk_protobuf_log_proto = out.File
	file_machinetalk_protobuf_log_proto_rawDesc = nil
	file_machinetalk_protobuf_log_proto_goTypes = nil
	file_machinetalk_protobuf_log_proto_depIdxs = nil
}
