// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: machinetalk/protobuf/sample.proto

package machinetalk_protobuf_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *uint64  `protobuf:"fixed64,1,opt,name=timestamp" json:"timestamp,omitempty"`
	VBytes    []byte   `protobuf:"bytes,2,opt,name=v_bytes,json=vBytes" json:"v_bytes,omitempty"`
	VInt32    *int32   `protobuf:"fixed32,3,opt,name=v_int32,json=vInt32" json:"v_int32,omitempty"`
	VInt64    *int64   `protobuf:"fixed64,4,opt,name=v_int64,json=vInt64" json:"v_int64,omitempty"`
	VUint32   *uint32  `protobuf:"fixed32,5,opt,name=v_uint32,json=vUint32" json:"v_uint32,omitempty"`
	VUint64   *uint64  `protobuf:"fixed64,6,opt,name=v_uint64,json=vUint64" json:"v_uint64,omitempty"`
	VDouble   *float64 `protobuf:"fixed64,7,opt,name=v_double,json=vDouble" json:"v_double,omitempty"`
	VString   *string  `protobuf:"bytes,8,opt,name=v_string,json=vString" json:"v_string,omitempty"`
	VBool     *bool    `protobuf:"varint,9,opt,name=v_bool,json=vBool" json:"v_bool,omitempty"`
}

func (x *Sample) Reset() {
	*x = Sample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_machinetalk_protobuf_sample_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_machinetalk_protobuf_sample_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_machinetalk_protobuf_sample_proto_rawDescGZIP(), []int{0}
}

func (x *Sample) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *Sample) GetVBytes() []byte {
	if x != nil {
		return x.VBytes
	}
	return nil
}

func (x *Sample) GetVInt32() int32 {
	if x != nil && x.VInt32 != nil {
		return *x.VInt32
	}
	return 0
}

func (x *Sample) GetVInt64() int64 {
	if x != nil && x.VInt64 != nil {
		return *x.VInt64
	}
	return 0
}

func (x *Sample) GetVUint32() uint32 {
	if x != nil && x.VUint32 != nil {
		return *x.VUint32
	}
	return 0
}

func (x *Sample) GetVUint64() uint64 {
	if x != nil && x.VUint64 != nil {
		return *x.VUint64
	}
	return 0
}

func (x *Sample) GetVDouble() float64 {
	if x != nil && x.VDouble != nil {
		return *x.VDouble
	}
	return 0
}

func (x *Sample) GetVString() string {
	if x != nil && x.VString != nil {
		return *x.VString
	}
	return ""
}

func (x *Sample) GetVBool() bool {
	if x != nil && x.VBool != nil {
		return *x.VBool
	}
	return false
}

var File_machinetalk_protobuf_sample_proto protoreflect.FileDescriptor

var file_machinetalk_protobuf_sample_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x6b, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x6b,
	0x1a, 0x21, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x6b, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x83, 0x02, 0x0a, 0x06, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x06, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x17, 0x0a, 0x07,
	0x76, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x76,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x5f, 0x69, 0x6e, 0x74, 0x33, 0x32,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0f, 0x52, 0x06, 0x76, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x17,
	0x0a, 0x07, 0x76, 0x5f, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x10, 0x52,
	0x06, 0x76, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x5f, 0x75, 0x69, 0x6e,
	0x74, 0x33, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x07, 0x52, 0x07, 0x76, 0x55, 0x69, 0x6e, 0x74,
	0x33, 0x32, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x5f, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x06, 0x52, 0x07, 0x76, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x19, 0x0a,
	0x08, 0x76, 0x5f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x07, 0x76, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x08, 0x76, 0x5f, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0x92, 0x3f, 0x02, 0x08,
	0x29, 0x52, 0x07, 0x76, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x76, 0x5f,
	0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x42, 0x6f, 0x6f,
	0x6c, 0x3a, 0x06, 0x92, 0x3f, 0x03, 0x48, 0xe9, 0x02, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x6b,
	0x69, 0x74, 0x2f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x6b, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x67, 0x6f,
}

var (
	file_machinetalk_protobuf_sample_proto_rawDescOnce sync.Once
	file_machinetalk_protobuf_sample_proto_rawDescData = file_machinetalk_protobuf_sample_proto_rawDesc
)

func file_machinetalk_protobuf_sample_proto_rawDescGZIP() []byte {
	file_machinetalk_protobuf_sample_proto_rawDescOnce.Do(func() {
		file_machinetalk_protobuf_sample_proto_rawDescData = protoimpl.X.CompressGZIP(file_machinetalk_protobuf_sample_proto_rawDescData)
	})
	return file_machinetalk_protobuf_sample_proto_rawDescData
}

var file_machinetalk_protobuf_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_machinetalk_protobuf_sample_proto_goTypes = []interface{}{
	(*Sample)(nil), // 0: machinetalk.Sample
}
var file_machinetalk_protobuf_sample_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_machinetalk_protobuf_sample_proto_init() }
func file_machinetalk_protobuf_sample_proto_init() {
	if File_machinetalk_protobuf_sample_proto != nil {
		return
	}
	file_machinetalk_protobuf_nanopb_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_machinetalk_protobuf_sample_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_machinetalk_protobuf_sample_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_machinetalk_protobuf_sample_proto_goTypes,
		DependencyIndexes: file_machinetalk_protobuf_sample_proto_depIdxs,
		MessageInfos:      file_machinetalk_protobuf_sample_proto_msgTypes,
	}.Build()
	File_machinetalk_protobuf_sample_proto = out.File
	file_machinetalk_protobuf_sample_proto_rawDesc = nil
	file_machinetalk_protobuf_sample_proto_goTypes = nil
	file_machinetalk_protobuf_sample_proto_depIdxs = nil
}
